services:
  nginx:
    image: nginx:alpine
    container_name: easyclaw-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./site:/usr/share/nginx/html:ro
      - ./certs/certbot/conf:/etc/letsencrypt:ro
      - ./certs/certbot/www:/var/www/certbot:ro
    restart: unless-stopped
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: easyclaw-certbot
    volumes:
      - ./certs/certbot/conf:/etc/letsencrypt
      - ./certs/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
